# Generated by Django 5.2.5 on 2025-11-03 00:15

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(help_text='Unique identifier (e.g., innovation, feasibility)', max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Description of what judges should evaluate')),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight should be between 0 and 1', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('order', models.IntegerField(default=0, help_text='Display order in evaluation form')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('locked', models.BooleanField(default=False, help_text='When locked, judges cannot edit scores')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='judges/')),
                ('image_path', models.CharField(blank=True, max_length=500)),
                ('organization', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='teams/')),
                ('image_path', models.CharField(blank=True, help_text='Alternative: file path or URL if not using ImageField', max_length=500)),
                ('short_description', models.TextField()),
                ('members', models.TextField(help_text='Semicolon-separated or JSON string')),
                ('extra_info', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['project_name'],
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('scores', models.JSONField(default=dict, help_text="Structure: {'innovation': {'score': 8, 'note': 'x'}, ...}")),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('general_comment', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='judging.judge')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='judging.team')),
            ],
            options={
                'ordering': ['-total', '-updated_at'],
                'unique_together': {('team', 'judge')},
            },
        ),
    ]
