# Generated by Django 5.2.5 on 2025-11-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judging', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='image',
        ),
        migrations.RemoveField(
            model_name='team',
            name='image_path',
        ),
        migrations.AddField(
            model_name='team',
            name='project_domain',
            field=models.CharField(blank=True, help_text="Project domain (e.g., 'Agriculture', 'Healthcare')", max_length=255),
        ),
        migrations.AddField(
            model_name='team',
            name='team_leader_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='team',
            name='team_leader_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='team',
            name='team_leader_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='team',
            name='team_leader_year',
            field=models.CharField(blank=True, help_text="Year of study (e.g., '3rd year')", max_length=50),
        ),
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.TextField(help_text='Team members - semicolon-separated or JSON string'),
        ),
        migrations.AlterField(
            model_name='team',
            name='short_description',
            field=models.TextField(help_text='Project summary'),
        ),
    ]
