# Generated by Django 5.2.5 on 2025-11-18 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judging', '0002_update_team_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='judge',
            name='image',
        ),
        migrations.RemoveField(
            model_name='judge',
            name='image_path',
        ),
        migrations.RemoveField(
            model_name='team',
            name='project_domain',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team_leader_email',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team_leader_name',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team_leader_phone',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team_leader_year',
        ),
    ]
