# Generated by Django 5.2.5 on 2025-11-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judging', '0003_remove_judge_image_remove_judge_image_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='project_domain',
            field=models.CharField(blank=True, help_text="Project domain (e.g., 'Agriculture', 'Healthcare')", max_length=255),
        ),
        migrations.AddField(
            model_name='team',
            name='team_leader_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='team',
            name='team_leader_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='team',
            name='team_leader_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
