# Generated by Django 5.2.5 on 2025-11-18 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judging', '0004_team_project_domain_team_team_leader_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_leader_year',
            field=models.CharField(blank=True, help_text="Year of study (e.g., '3rd year')", max_length=50),
        ),
    ]
