# Generated by Django 5.2.7 on 2025-11-21 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judging', '0005_team_team_leader_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criterion',
            name='key',
            field=models.CharField(blank=True, help_text='Auto-generated unique identifier (e.g., innovation, feasibility)', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='criterion',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order in evaluation form - must be unique', unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='project_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='short_description',
            field=models.TextField(help_text='Project summary - no length limit'),
        ),
        migrations.AddConstraint(
            model_name='criterion',
            constraint=models.UniqueConstraint(fields=('order',), name='unique_criterion_order'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('project_name',), name='unique_project_name'),
        ),
    ]
