# Generated by Django 5.2.7 on 2025-11-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judging', '0007_simplify_team_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='nom_equipe',
            field=models.CharField(max_length=255),
        ),
    ]
